### ISSUE TITLE
Configuration file request.

### ISSUE THREAD

**Issue by lo-corp** [loeffel-io/ls-lint#41] opened 2021-01-14 22:46 UTC
It doesn't look good when you're forced to use only .yml file extension.

I want to store the config in ls-lint.yaml, and I'm sure some people would like the configs in json format as well. is it possible?

Afaik there're some pre-built tools to enable this behaviour.

https://github.com/search?o=desc&q=config+json+yaml&s=stars&type=Repositories

**Comment by loeffel-io** [comment] 2021-01-15 08:41
Duplicate of #29 and mentioned in #36

**Closed by loeffel-io** 2021-01-15 08:41 UTC
