### ISSUE TITLE
Feature request: Allow passing files via argv

### ISSUE THREAD

**Issue by binary64** [loeffel-io/ls-lint#53] opened 2021-05-07 19:30 UTC
So that we can use ls-lint from lint-staged, where it passes git staged files as command arguments such as:
```
node_modules/.bin/ls-lint file1.js path/to/file2.js
```
The result would be an insanely fast execution.

**Comment by loeffel-io** [comment] 2021-05-17 08:25
duplicate of #40

**Closed by loeffel-io** 2021-05-17 08:25 UTC
